"""update

Revision ID: b83b5b968f93
Revises: 07963c72e888
Create Date: 2023-06-28 19:27:02.267154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83b5b968f93'
down_revision = '07963c72e888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('cosmos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('mass', sa.String(length=200), nullable=True),
    sa.Column('radius', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('period', sa.String(length=150), nullable=True),
    sa.Column('semi_major_axis', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.String(length=100), nullable=True),
    sa.Column('distance_light_year', sa.String(length=100), nullable=True),
    sa.Column('host_star_mass', sa.String(length=100), nullable=True),
    sa.Column('host_star_temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('random_joke', sa.String(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cosmos')
    op.drop_table('user')
    # ### end Alembic commands ###
